version: "3.3"

services:
  # MySQL
  mysql:
    image: mysql:latest
    volumes:
      - ./db-course.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db-course
  # web
  web:
    image : springboot_course:latest
    depends_on:
      - mysql
    ports:
      - "8089:8080"
    restart: always