version: "3.8"

services:
    # MySQL
    db:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123
        networks:
            - mysql
    # phpmyadmin
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - "82:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: 123
        networks:
            - mysql
networks:
    mysql:
volumes:
    db_data:
