version: "3.3"

services:
    # Nginx
    # MySQL
    mysql:
        image: mysql:latest
        volumes:
            - ./db-course.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123
        networks:
            - project_network

    # PhpMyAdmin
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - "89:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: 123
        networks:
            - project_network

    # Course
    course:
        image: buihien0109/springboot_course:latest
        depends_on:
            - mysql
        ports:
            - "8089:8080"
        restart: always
        networks:
            - project_network

    # Blog
    blog:
        image: buihien0109/springboot_blog:latest
        depends_on:
            - mysql
        ports:
            - "8090:8080"
        restart: always
        networks:
            - project_network
